//Stacks are defined here
export const NAVIGATION_AUTH_LOADING_STACK: string =
  'NAVIGATION_AUTH_LOADING_STACK';
export const NAVIGATION_AUTH_STACK: string = 'NAVIGATION_AUTH_STACK';
export const NAVIGATION_TRADE_STACK: string = 'NAVIGATION_TRADE_STACK';
export const NAVIGATION_BOTTOM_TAB_STACK: string =
  'NAVIGATION_BOTTOM_TAB_STACK';

//Screens are defined here
export const NAVIGATION_AUTH_LOADING_SCREEN: string =
  'NAVIGATION_AUTH_LOADING_SCREEN';
export const WELCOME_SCREEN: string = 'WELCOME_SCREEN';
export const LOGIN_SCREEN: string = 'LOGIN_SCREEN';
export const ONBOARDING_CDD_SCREEN: string = 'ONBOARDING_CDD_SCREEN';
export const REGISTER_SCREEN: string = 'REGISTER_SCREEN';
export const SET_PASSWORD_SCREEN: string = 'SET_PASSWORD_SCREEN';
export const VERIFY_ACCOUNT_SCREEN: string = 'VERIFY_ACCOUNT_SCREEN';
export const ACCOUNT_ACTIVATED_SCREEN: string = 'ACCOUNT_ACTIVATED_SCREEN';
export const FORGOT_PASSWORD_SCREEN: string = 'FORGOT_PASSWORD_SCREEN';
export const OTP_VERIFY_SCREEN: string = 'OTP_VERIFY_SCREEN';
export const AUTH_VERIFICATION_SCREEN: string = 'AUTH_VERIFICATION_SCREEN';
export const RESET_PASSWORD_SCREEN: string = 'RESET_PASSWORD_SCREEN';
export const HOME_SCREEN: string = 'HOME_SCREEN';
export const SEARCH_SCREEN: string = 'SEARCH_SCREEN';
export const TRADE_SCREEN: string = 'TRADE_SCREEN';
export const SWAPNEXBCOIN_SCREEN: string = 'SWAPNEXBCOIN_SCREEN';
export const WALLET_SCREEN: string = 'WALLET_SCREEN';
export const FUTURES_SCREEN: string = 'FUTURES_SCREEN';
export const ACCOUNT_SCREEN: string = 'ACCOUNT_SCREEN';
export const NOTIFICATION_SCREEN: string = 'NOTIFICATION_SCREEN';
export const EDIT_PROFILE_SCREEN: string = 'EDIT_PROFILE_SCREEN';
export const NOTIFICATION_SETTINGS_SCREEN: string =
  'NOTIFICATION_SETTINGS_SCREEN';
export const DIRECT_MESSAGE_MANAGEMENT_SCREEN: string =
  'DIRECT_MESSAGE_MANAGEMENT_SCREEN';
export const NICKNAME_SETTINGS_SCREEN: string = 'NICKNAME_SETTINGS_SCREEN';
export const SWITCH_ACCOUNT_SCREEN = "SWITCH_ACCOUNT_SCREEN";
export const SETTINGS_SCREEN: string = 'SETTINGS_SCREEN';
export const KYC_VERIFICATION_SCREEN: string = 'KYC_VERIFICATION_SCREEN';
export const KYC_RESUBMIT_SCREEN: string = 'KYC_RESUBMIT_SCREEN';
export const KYC_STATUS_SCREEN: string = 'KYC_STATUS_SCREEN';

export const INVITE_AND_EARN_SCREEN: string = 'INVITE_AND_EARN_SCREEN';
export const REFFERAL_TREE = "REFFERAL_TREE";
export const CONTACT_US_SCREEN: string = 'CONTACT_US_SCREEN';
export const CHANGE_PASSWORD_SCREEN: string = 'CHANGE_PASSWORD_SCREEN';
export const CURRENCY_PREFERENCE_SCREEN: string = 'CURRENCY_PREFERENCE_SCREEN';
export const COIN_DETAILS_SCREEN: string = 'COIN_DETAILS_SCREEN';
export const DEPOSIT_SCREEN: string = 'DEPOSIT_SCREEN';
export const WITHDRAW_SCREEN: string = 'WITHDRAW_SCREEN';
export const CONVERT_SCREEN: string = 'CONVERT_SCREEN';
export const BUY_CRYPTO_SCREEN: string = 'BUY_CRYPTO_SCREEN';
export const DEPOSIT_FIAT_SCREEN: string = 'DEPOSIT_FIAT_SCREEN';
export const DEPOSIT_FIAT_HISTORY_SCREEN: string = 'DEPOSIT_FIAT_HISTORY_SCREEN';
export const WITHDRAW_FIAT_SCREEN: string = 'WITHDRAW_FIAT_SCREEN';
export const WITHDRAW_FIAT_HISTORY_SCREEN: string = 'WITHDRAW_FIAT_HISTORY_SCREEN';
export const WALLET_DETAIL_SCREEN: string = 'WALLET_DETAIL_SCREEN';
export const DEPOSIT_INR_SCREEN: string = 'DEPOSIT_INR_SCREEN';
export const WITHDRAW_INR_SCREEN: string = 'WITHDRAW_INR_SCREEN';
export const WALLET_HISTORY_DETAILS_SCREEN: string =
  'WALLET_HISTORY_DETAILS_SCREEN';
export const DEPOSIT_HISTORY_DETAIL_SCREEN: string =
  'DEPOSIT_HISTORY_DETAIL_SCREEN';
export const TRADE_HISTORY_DETAILS_SCREEN: string =
  'TRADE_HISTORY_DETAILS_SCREEN';
export const PAYMENT_OPTIONS_SCREEN: string = 'PAYMENT_OPTIONS_SCREEN';
export const TRADE_SETTINGS_SCREEN: string = 'TRADE_SETTINGS_SCREEN';
export const FEE_SETTINGS_SCREEN: string = 'FEE_SETTINGS_SCREEN';
export const DOWNLOAD_TRADE_REPORT_SCREEN: string =
  'DOWNLOAD_TRADE_REPORT_SCREEN';
export const UPDATE_KGIN_SCREEN: string = 'UPDATE_KGIN_SCREEN';
export const COIN_DETAILS_CHART_SCREEN: string = 'COIN_DETAILS_CHART_SCREEN';
export const COIN_TRANSACTION_HISTORY_SCREEN: string =
  'COIN_TRANSACTION_HISTORY_SCREEN';
export const TWO_FACTOR_QR_SCREEN: string = 'TWO_FACTOR_QR_SCREEN';
export const ADD_PHONE_NUMBER_SCREEN: string = 'ADD_PHONE_NUMBER_SCREEN';
export const PHONE_SETTINGS_SCREEN: string = 'PHONE_SETTINGS_SCREEN';
export const UNLINK_PHONE_NUMBER_SCREEN: string = 'UNLINK_PHONE_NUMBER_SCREEN';
export const UNLINK_SUCCESS_SCREEN: string = 'UNLINK_SUCCESS_SCREEN';
export const ADD_EMAIL_SCREEN: string = 'ADD_EMAIL_SCREEN';
export const WITHDRAWAL_SETTINGS_SCREEN: string = 'WITHDRAWAL_SETTINGS_SCREEN';
export const WITHDRAWAL_VERIFY_EMAIL_SCREEN: string = 'WITHDRAWAL_VERIFY_EMAIL_SCREEN';
export const WITHDRAWAL_VERIFY_PHONE_SCREEN: string = 'WITHDRAWAL_VERIFY_PHONE_SCREEN';
export const SETUP_TWO_FACTOR_SCREEN: string = 'SETUP_TWO_FACTOR_SCREEN';
export const VERIFY_AUTHENTICATOR_CODE_SCREEN: string = 'VERIFY_AUTHENTICATOR_CODE_SCREEN';
export const ADD_PASSKEY_SCREEN: string = 'ADD_PASSKEY_SCREEN';

export const VIEW_PASSKEYS_SCREEN: string = 'VIEW_PASSKEYS_SCREEN';
export const PASSKEY_SCREEN: string = 'PASSKEY_SCREEN';
export const PASSKEY_ADD_PHONE_SCREEN: string = 'PASSKEY_ADD_PHONE_SCREEN';
export const PASSKEY_SECURITY_VERIFICATION_SCREEN: string = 'PASSKEY_SECURITY_VERIFICATION_SCREEN';
export const SECURITY_VERIFICATION_UNAVAILABLE_SCREEN: string = 'SECURITY_VERIFICATION_UNAVAILABLE_SCREEN';
export const SECURITY_PASSKEY_VERIFICATION_SCREEN: string = 'SECURITY_PASSKEY_VERIFICATION_SCREEN';
export const SECURITY_FACIAL_VERIFICATION_SCREEN: string = 'SECURITY_FACIAL_VERIFICATION_SCREEN';
export const CHANGE_PHONE_NUMBER_SCREEN: string = 'CHANGE_PHONE_NUMBER_SCREEN';
export const LOGIN_TWO_STEP_VERIFICATION_SCREEN: string = 'LOGIN_TWO_STEP_VERIFICATION_SCREEN';
export const DOWNLOAD_AUTHENTICATOR_SCREEN: string = 'DOWNLOAD_AUTHENTICATOR_SCREEN';
export const PASSKEY_SETUP_AUTHENTICATOR_SCREEN: string = 'PASSKEY_SETUP_AUTHENTICATOR_SCREEN';
export const DISABLE_2FA_SCREEN: string = 'DISABLE_2FA_SCREEN';
export const ENTER_OTP_SCREEN: string = 'ENTER_OTP_SCREEN';
export const LANGUAGE_PREFERENCE_SCREEN: string = 'LANGUAGE_PREFERENCE_SCREEN';
export const QUICK_BUY_SELL: string = 'QUICK_BUY_SELL';
export const QS_TRANSACTION: string = 'QS_TRANSACTION';

export const p2pOrder: string = 'p2pOrder';
export const p2pProfile: string = 'p2pProfile';
export const p2pAds: string = 'p2pAds';
export const p2pFilter: string = 'p2pFilter';
export const BUY_CRYPTO: string = 'buyCrypto';
export const ORDER_CREATED: string = 'ORDER_CREATED';
export const TRADE: string = 'TRADE';
export const ORDER_HISTORY = "ORDER_HISTORY";
/** Full list of spot open orders (`OpenOrder.js`). */
export const OPEN_ORDER_SCREEN = "Open_Order";
export const SPOT_ORDER_HISTORY_DETAIL = "SPOT_ORDER_HISTORY_DETAIL";
export const FUTURE_ORDER_HISTORY = "FUTURE_ORDER_HISTORY";
export const MARGIN_HISTORY_SCREEN = "MARGIN_HISTORY_SCREEN";
export const PROJECT_COMMIT = 'PROJECT_COMMIT';
export const COMMIT_DETAIL = "COMMIT_DETAIL";
export const REFERRAL_LIST = "REFERRAL_LIST";
export const REFER_AND_EARN_SCREEN = 'REFER_AND_EARN_SCREEN';
export const WALLET_HISTORY_SCREEN = 'WALLET_HISTORY_SCREEN';
export const MARKET_SCREEN = 'MARKET_SCREEN';
export const SPOT_MARKET_SCREEN = 'SPOT_MARKET_SCREEN';
export const SPOT_CHART_SCREEN = 'SPOT_CHART_SCREEN';
export const MARGIN_BORROW_REPAY_SCREEN = 'MARGIN_BORROW_REPAY_SCREEN';
export const MARGIN_BORROW_REPAY_HISTORY_SCREEN = 'MARGIN_BORROW_REPAY_HISTORY_SCREEN';
export const MARGIN_TRANSFER_SCREEN = 'MARGIN_TRANSFER_SCREEN';
export const TRANSFER_HISTORY_SCREEN = 'TRANSFER_HISTORY_SCREEN';
export const MARGIN_TRANSFER_HISTORY_SCREEN = 'MARGIN_TRANSFER_HISTORY_SCREEN';
export const MORE_MENU_SCREEN = "MORE_MENU_SCREEN";
export const EARING_SCREEN = "EARING_SCREEN";
export const TRANSFER_SCREEN = "TRANSFER_SCREEN";
export const DEPOSIT_WALLET_SCREEN = "DEPOSIT_WALLET_SCREEN";
export const DEPOSIT_COIN_SCREEN = "DEPOSIT_COIN_SCREEN";
export const WALLET_WITHDRAW_SCREEN = "WALLET_WITHDRAW_SCREEN";
export const AIRDROP_SCREEN = "AIRDROP_SCREEN";
export const AIRDROP_HISTORY_SCREEN = "AIRDROP_HISTORY_SCREEN";
// export const EARING_SCREEN
export const ARBITORY_SCREEN = 'ArbitoryBot'
export const Dashboard_Inner = 'DashboardInnder'


export const kyc_Details = 'kycDetails'
export const SECURITY = "Security"
export const SETTING_SCREEN_New = 'SettingsScreen'
export const OPTIONS_SCREEN = 'OPTIONS_SCREEN'
export const BUY_OPTIONS_SCREEN = 'BUY_OPTIONS_SCREEN'
export const OPTIONS_HISTORY_SCREEN = 'OPTIONS_HISTORY_SCREEN'
export const OPTIONS_PNL_ANALYSIS_SCREEN = 'OptionsPnlAnalysis'
export const SPOT_PNL_ANALYSIS_SCREEN = 'SpotPnlAnalysis'
export const ANTI_PHISHING_CODE_SCREEN: string = 'ANTI_PHISHING_CODE_SCREEN';
export const CREATE_ANTI_PHISHING_SCREEN: string = 'CREATE_ANTI_PHISHING_SCREEN';
export const EDIT_ANTI_PHISHING_SCREEN: string = 'EDIT_ANTI_PHISHING_SCREEN';
export const DISABLE_ANTI_PHISHING_SCREEN: string = 'DISABLE_ANTI_PHISHING_SCREEN';
export const REMOVE_ANTI_PHISHING_SCREEN: string = 'REMOVE_ANTI_PHISHING_SCREEN';
export const RESET_PASSWORD_FROM_CHANGE: string = 'RESET_PASSWORD_FROM_CHANGE';

/** Create a new support ticket (separate screen; list remains route name `Support`). */
export const CREATE_TICKET_SCREEN = 'CreateTicket';
export const WITHDRAW_HISTORY_SCREEN = 'WITHDRAW_HISTORY_SCREEN';
export const WITHDRAW_DETAIL_SCREEN = 'WITHDRAW_DETAIL_SCREEN';
export const SELECT_COIN_SCREEN = 'SELECT_COIN_SCREEN';
export const WITHDRAW_FORM_SCREEN = 'WITHDRAW_FORM_SCREEN';

export const ADD_FAVOURITE_SCREEN = 'ADD_FAVOURITE_SCREEN';

export const EMERGENCY_CONTACT_SCREEN: string = 'EMERGENCY_CONTACT_SCREEN';
export const ADD_EMERGENCY_CONTACT_SCREEN: string = 'ADD_EMERGENCY_CONTACT_SCREEN';
export const EMERGENCY_CONTACT_VERIFICATION_SCREEN: string = 'EMERGENCY_CONTACT_VERIFICATION_SCREEN';
export const CONFIRM_EMERGENCY_CONTACT_SCREEN: string = 'CONFIRM_EMERGENCY_CONTACT_SCREEN';
export const ACCOUNT_CONNECTIONS_SCREEN: string = 'ACCOUNT_CONNECTIONS_SCREEN';
export const FUND_PASSWORD_MAIN_SCREEN: string = 'FUND_PASSWORD_MAIN_SCREEN';
export const CHANGE_FUND_PASSWORD_SCREEN: string = 'CHANGE_FUND_PASSWORD_SCREEN';
export const RESET_FUND_PASSWORD_SCREEN: string = 'RESET_FUND_PASSWORD_SCREEN';
export const FUND_PASSWORD_RESET_SUCCESS_SCREEN: string = 'FUND_PASSWORD_RESET_SUCCESS_SCREEN';
export const CHANGE_LOGIN_PASSWORD_SCREEN: string = 'CHANGE_LOGIN_PASSWORD_SCREEN';
export const RESET_YOUR_PASSWORD_SCREEN: string = 'RESET_YOUR_PASSWORD_SCREEN';
export const AUTHORIZED_DEVICES_SCREEN: string = 'AUTHORIZED_DEVICES_SCREEN';
export const SECURITY_LOGS_SCREEN: string = 'SECURITY_LOGS_SCREEN';
export const DISABLE_ACCOUNT_SCREEN: string = 'DISABLE_ACCOUNT_SCREEN';
export const THIRD_PARTY_ACCOUNT_ACCESS_SCREEN: string = 'THIRD_PARTY_ACCOUNT_ACCESS_SCREEN';
export const CLOSE_ACCOUNT_REASON_SCREEN: string = 'CLOSE_ACCOUNT_REASON_SCREEN';
export const PERSONAL_PAGE_SCREEN: string = 'PERSONAL_PAGE_SCREEN';
export const CONVERT_HISTORY_SCREEN: string = 'CONVERT_HISTORY_SCREEN';
export const STAKING_DASHBOARD_SCREEN: string = 'STAKING_DASHBOARD_SCREEN';
export const EARNING_SCREEN: string = 'EARNING_SCREEN';
export const SOFT_STAKING_SCREEN: string = 'SOFT_STAKING_SCREEN';
export const VIP_SERVICES_SCREEN: string = 'VIP_SERVICES_SCREEN';
export const LAUNCHPAD_SCREEN: string = 'LAUNCHPAD_SCREEN';
export const LAUNCHPAD_DETAIL_SCREEN: string = 'LAUNCHPAD_DETAIL_SCREEN';
